name: Django Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            whoami
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git pull
            source env/bin/activate
            python backend/manage.py collectstatic
            python backend/manage.py makemigrations
            python backend/manage.py migrate
            echo ${{ secrets.SERVER_USER_PASSWORD }} | sudo -S systemctl restart gunicorn
